#############################################################################################
# Incluir aqui las propiedades a utilizar por Spring Boot y los componentes de la aplicaci√≥n #
##############################################################################################
# ===================================================================
# Spring Boot configuration properties
# ===================================================================
logging:
  level:
    es.giss.arch: DEBUG

spring:

  server:
    port: 8080
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ldap://oraoid1.portal.ss:389/ds32,cn=OracleContext,dc=portal,dc=ss
    username: MACA_ITINERARIO
    password: maca_itinerario
  web:
    ignoreAutoConfiguredSkipPatterns: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
kafka:
  bootstrap:
    servers: localhost

# ===================================================================
# Giss framework properties
# ===================================================================
giss:

  audit:
    enabled: false

  security:
    web:
      fake:
        enabled: true
        roles: ROLE_GISS_ACTUATOR
        authorities: READ_FAKE, WRITE_FAKE
        type-of-user: INTRANET

  webclient:
    basic-auth-config:
      user: test
      password: test

    kafka:
    #en local se desactiva la seguridad de kafka
      ssl:
        truststore:
          location: C:\\Users\\99GU3997
      default-config:
        secured-connection:
          enabled: false

    monitoring:
    #entorno
      environment: local


